on: [push]

jobs:
  build_latex:
    name: Build lecture PDFs
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Build figures
        uses: ./lecture/
        with:
          run: make figures

      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            apk add git
            cd lecture
            make all-wo-figures

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Lecture Slides
          path: |
            lecture/output/*.pdf
            lecture/output/*.log
          retention-days: 5
