on: [push]

jobs:
  build_latex:
    name: Build lecture PDFs
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            apk add git
            cd lecture
            for filename in *.tex; do
            make vc.tex
            make "${filename%.*}.pdf"
            make "${filename%.*}.bbl"
            done

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Lecture Slides
          path: lecture/*.pdf
          retention-days: 5
