name: Build LaTeX documents

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            cd lecture
            for filename in *.tex; do
            make "${filename%.*}.pdf"
            make "${filename%.*}.bbl"
            done
