on: [push]

jobs:
  build_latex:
    name: Build lecture PDFs
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            apk add git
            echo "http://dl-cdn.alpinelinux.org/alpine/latest-stable/main" > /etc/apk/repositories
            echo "http://dl-cdn.alpinelinux.org/alpine/latest-stable/community" >> /etc/apk/repositories
            apk --no-cache --update-cache add gcc gfortran python python-dev py-pip build-base wget freetype-dev libpng-dev openblas-dev
            ln -s /usr/include/locale.h /usr/include/xlocale.h
            apk --no-cache add musl-dev linux-headers g++
            apk add py3-pip python3
            cd lecture
            pip3 install -r src/requirements.txt
            make all

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Lecture Slides
          path: |
            lecture/output/*.pdf
            lecture/output/*.log
          retention-days: 5
